#!/bin/sh
### Set a couple variables
export KERNDIR=$HOME\/.cache/autoKern
export AUTOKERNCONF=$HOME\/.config/autoKern
mkdir -p $KERNDIR
mkdir -p $AUTOKERNCONF
export VERBAGE=/dev/stdout
export DLCOM="curl -LO"
export COMPTHREADS=`nproc`
cd $KERNDIR
echo "Enter a kernel version: "
read KERNVER
export KERNVER=$KERNVER
[ -z $KERNVER ] && export KERNVER=`curl https://www.kernel.org/ | grep -A 1 latest_link | grep -o -P '(?<=.tar.xz">).*(?=</a>)'`
export KERNPREFIX=`echo $KERNVER | cut -c1`
COUNT=1
while [ -f /boot/vmlinuz-linux_$KERNVER\_$COUNT ];
do
	let COUNT+=1
done
export COUNT=$COUNT
### Get source code
dlSource()
(
echo $KERNDIR $VERBAGE $DLCOM $KERNVER $KERNPREFIX $COUNT $COMPTHREADS
$DLCOM https://cdn.kernel.org/pub/linux/kernel/v$KERNPREFIX.x/linux-$KERNVER.tar.xz #&>$VERBAGE
)
## Verbose download
vdlSource()
(
$DLCOM\v https://cdn.kernel.org/pub/linux/kernel/v$KERNPREFIX.x/linux-$KERNVER.tar.xz
)
### Extract source code
extract()
(
tar -xJf linux-$KERNVER.tar.xz || echo "invalid kernel version"; exit 1
)
## Verbose alternative extract
vextract()
(
tar -xvJf linux-$KERNVER.tar.xz || echo "invalid kernel version"; exit 1
)
vkernconf()
(
cp -v $AUTOKERNCONF/kernconf .config || zcat /proc/config.gz > .config || make defconfig
mv -f -v $AUTOKERNCONF/kernconf $AUTOKERNCONF/kernconf.old
cp -v .config $AUTOKERNCONF/kernconf
)
kernconf()
(
cp $AUTOKERNCONF/kernconf .config || zcat /proc/config.gz > .config || make defconfig
mv -f $AUTOKERNCONF/kernconf $AUTOKERNCONF/kernconf.old
cp .config $AUTOKERNCONF/kernconf
)
make()
(
make -j$COMPTHREADS #&>$VERBAGE
sudo make modules_install #&>$VERBAGE
)
## Verbose alternative make
vmake()
(
make --debug=v -j$COMPTHREADS
sudo make --debug=v -j$COMPTHREADS modules_install
)
### copy bzImage
bzimg()
(
sudo cp arch/x86_64/boot/bzImage /boot/vmlinuz-linux_$KERNVER\_$COUNT
)
## Verbose alternative copy bz
vbzimg()
(
sudo cp -v arch/x86_64/boot/bzImage /boot/vmlinuz-linux_$KERNVER\_$COUNT
)
### initramfs & systemmap
initmap()
(
sudo mkinitcpio -k $KERNVER -g /boot/initramfs-linux_$KERNVER\_$COUNT #&>$VERBAGE
sudo cp System.map /boot/System.map-linux_$KERNVER\_$COUNT
)
## Verbose alternative initramfs & systemmap
vinitmap()
(
sudo mkinitcpio -v -k $KERNVER -g /boot/initramfs-linux_$KERNVER\_$COUNT
sudo cp -v System.map /boot/System.map-linux_$KERNVER\_$COUNT
)
### Get passed options
while getopts ":hvsw:" option; do
   case $option in
      h) # display help
         echo "type 'man autokern'"
         exit 0;;
      v) # Verbose
	      AUTOKERNVERB = v;;
      s) # Silent
		VERBAGE=/dev/null;;
      w) # Wget
		DLCOM="wget -v";;
     \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done
### Actually run the code
$AUTOKERNVERB\dlSource
$AUTOKERNVERB\extract
cd linux-$KERNVER
$AUTOKERNVERB\kernconf
$AUTOKERNVERB\make
$AUTOKERNVERB\bzimg
$AUTOKERNVERB\initmap
unset AUTOKERNVERB
exit
